services:
  bot:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
      cache_from:
        - golang:1.23.6
    container_name: gotasks_bot
    networks:
      - gotasks_network
    develop:
      watch:
        - action: rebuild
          path: ../..

volumes:
  gotasks_data:

networks:
  gotasks_network: